#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          icetunnel
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: IceTunnel
# Description:       IceTunnel
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/usr/local/bin/icetunnel
NAME=icetunnel
DESC="IceTunnel"
PARAMS="--tcp-listener 127.0.0.1:1080 1.2.3.4:1234"

start() {
    log_daemon_msg "Starting $DESC" "$NAME"
    start-stop-daemon --start --quiet --background --pidfile /var/run/$NAME.pid --make-pidfile --exec $DAEMON -- $PARAMS
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping $DESC" "$NAME"
    start-stop-daemon --stop --oknodo --quiet --pidfile /var/run/$NAME.pid --remove-pidfile --retry 5
    log_end_msg $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
esac

exit 0
